const symbol='https://raw.githubusercontent.com/2030Retire/ezworks-site/master/public/ezworks-symbol.png';
const products=[
  ['⌁','Recorder','Record. Transcribe. Remember.','Turn meetings and conversations into organized, searchable knowledge.'],
  ['▤','Expense','Capture. Review. Publish.','Move receipts from capture to review and clean accounting-ready data.'],
  ['▧','Invoice','Create. Track. Get paid.','Create invoices, send them easily, and keep payment visibility in one place.'],
  ['◆','Class','Members. Classes. Attendance. Progress.','Manage members, schedules, attendance and progression for class-based businesses.']
];
const steps=[['01','Understand the work'],['02','Define the process'],['03','Fix inputs & outputs'],['04','Connect the data'],['05','Automate'],['06','Add AI where useful']];
function Mark({icon,name}:{icon:string,name:string}){return <div className="mark"><img src={symbol} alt=""/><span className="bar"/><span className="picon">{icon}</span><span><b><i>EZ</i>Haru</b><small>{name}</small></span></div>}
export default function Home(){return <>
<section className="hero"><div className="shell heroGrid"><div className="heroCopy"><div className="eyebrow">PEOPLE + PROCESS + A SMARTER TOMORROW</div><h1>Making every<br/>workday easier.</h1><p>We help small and mid-sized businesses simplify everyday work with practical systems, automation and AI.</p><div className="actions"><a className="btn" href="#solutions">Explore Solutions →</a><a className="btn ghost" href="#products">Explore Products</a></div><div className="trust"><span>✓ Real business experience</span><span>✓ Practical solutions</span><span>✓ Measurable outcomes</span></div></div><div className="stage"><div className="note">Less work.<br/>More what matters.</div><div className="screen"><aside><strong><em>EZ</em> EZHaru</strong><a>⌂ Home</a><a>⌁ Recorder</a><a>▤ Expense</a><a>▧ Invoice</a><a>◆ Class</a><span></span><a>⚙ Settings</a></aside><section><h3>Good morning!</h3><p>Everything in one place. A simpler workday ahead.</p><div className="search">Search anything...</div><div className="miniGrid">{products.map(([icon,name,,copy])=><div className="mini" key={name}><b>{icon}</b><strong>{name}</strong><small>{copy.split('.')[0]}.</small></div>)}</div></section><aside className="today"><strong>Today</strong><a>✓ Receipts processed</a><a>✓ Invoices sent</a><a>✓ Member updates</a><a>✓ Systems running smoothly</a></aside></div><div className="phone"><span></span><strong><em>EZ</em><br/>EZHaru</strong>{products.map(([icon,name])=><a key={name}>{icon} {name}<b>›</b></a>)}</div></div></div></section>
<section id="solutions" className="section"><div className="shell"><div className="center intro"><div className="eyebrow">TWO WAYS WE HELP</div><h2>From understanding to real results.</h2><p>Whether you need hands-on support or focused software, EZHaru meets you where you are.</p></div><div className="help"><article><span className="circle">◎</span><div><h3>Consulting & Solutions</h3><p>We study how the work actually happens, define the process, connect the systems and automate what makes sense.</p><a href="mailto:hello@ezharu.co">Explore Solutions →</a></div></article><article><span className="circle">◇</span><div><h3>EZHaru Products</h3><p>Simple, practical tools built around real operational problems and designed for everyday work.</p><a href="#products">Explore Products →</a></div></article></div></div></section>
<section id="products" className="section products"><div className="shell"><div className="heading"><div><div className="eyebrow">OUR PRODUCTS</div><h2>Tools for a simpler workday.</h2><p>Four focused tools. One EZHaru family.</p></div></div><div className="cards">{products.map(([icon,name,headline,copy])=><article key={name}><Mark icon={icon} name={name}/><h3>{headline}</h3><p>{copy}</p><a href="mailto:hello@ezharu.co">Learn more →</a></article>)}</div></div></section>
<section id="approach" className="section approach"><div className="shell approachGrid"><div><div className="eyebrow">OUR APPROACH</div><h2>Groundwork before AI.</h2><p>AI works best when your processes, data and systems are ready. We help you build that foundation first.</p><a className="btn ghost" href="mailto:hello@ezharu.co">See How We Work →</a></div><div className="steps">{steps.map(([n,t],i)=><div key={n}><span>{n}</span><b>{t}</b>{i<steps.length-1&&<i>→</i>}</div>)}</div></div></section>
<section className="section review"><div className="shell reviewGrid"><div><div className="eyebrow">START SMARTER</div><h2>Two-Week Operational Review</h2><h3>$2,400 fixed price</h3><p>We review your current operations, identify practical opportunities and deliver a roadmap you can act on. If you move forward with implementation, the review fee can be credited toward the work.</p><a className="btn" href="mailto:hello@ezharu.co">Request a Review →</a></div><article><small>WHAT YOU LEAVE WITH</small><p><b>01</b> Current-state map</p><p><b>02</b> Prioritized opportunities</p><p><b>03</b> Practical roadmap</p></article><article><small>TECHNOLOGY EXPERIENCE</small><div className="chips"><span>SAP</span><span>Microsoft 365</span><span>Power Platform</span><span>Salesforce</span><span>QuickBooks</span><span>ERP / WMS / CRM</span></div></article></div></section>
<section id="about" className="principles"><div className="shell"><span>Built around real operations.</span><b>Practical systems.</b><b>Clear processes.</b><b>Useful automation.</b><b>AI where it actually helps.</b></div></section>
</>}
