import {notFound} from 'next/navigation';
import Link from 'next/link';
import {CTA, Icon, ProductKey, ProductMark, productInfo} from '@/components/BrandSystem';

const keys:ProductKey[]=['recorder','expense','invoice','class'];
const details:Record<ProductKey,{headline:string;sub:string;features:[string,string,string][];flow:string[];closing:string}>={
 recorder:{headline:'Capture the conversation. Keep the knowledge.',sub:'From calls and meetings to transcripts, summaries and searchable follow-up — without turning note-taking into another job.',features:[['wave','Reliable capture','Keep conversations available for review instead of relying on memory.'],['document','Clear transcription & summaries','Turn spoken information into useful written context.'],['search','Find what matters later','Make past discussions easier to revisit and act on.'],['link','Share useful knowledge','Keep important context available to the people who need it.']],flow:['Record','Transcribe','Summarize','Organize','Search & reuse'],closing:'Less note-taking. More attention on the actual conversation.'},
 expense:{headline:'Receipts in. Clean expense data out.',sub:'Capture receipts, review the details, approve what matters and prepare clean information for the accounting workflow.',features:[['receipt','Simple receipt capture','Bring receipts in from the channels people already use.'],['document','Structured extraction','Turn receipt details into reviewable expense information.'],['search','Review before publish','Keep a human check where it matters instead of blindly automating.'],['link','Ready for accounting workflows','Prepare clean data for the next system or review step.']],flow:['Capture','Extract','Review','Approve','Publish'],closing:'Less time chasing receipts. More time on accurate books.'},
 invoice:{headline:'Invoicing made simple and visible.',sub:'Create invoices clearly, send them consistently and keep a practical view of what has been billed and what still needs attention.',features:[['document','Professional invoices','Create clean, consistent invoices from a simple workflow.'],['link','Send & track','Keep invoice delivery and follow-up visible.'],['search','Payment visibility','Know what is open without digging through disconnected files.'],['gear','Repeatable workflow','Reduce manual steps for recurring invoicing work.']],flow:['Create','Review','Send','Track','Follow up'],closing:'Clear invoicing. Better visibility. Fewer loose ends.'},
 class:{headline:'Manage the class business, not just the calendar.',sub:'EZHaru Class starts with martial arts schools and is designed to grow into a flexible platform for class-based businesses.',features:[['people','Member management','Keep member information organized and easy to work with.'],['document','Schedules & attendance','Manage class schedules and track participation.'],['layers','Progress & rank','Support belt, rank or level progression without locking the product to one industry.'],['link','Communication & operations','Create a clearer operating flow around the people and classes.']],flow:['Members','Schedule','Attendance','Progress','Communication'],closing:'Built for dojang operations today, with room for other class-based businesses tomorrow.'}
};

export function generateStaticParams(){return keys.map(slug=>({slug}));}

export default async function ProductPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;if(!keys.includes(slug as ProductKey))notFound();const key=slug as ProductKey;const p=productInfo[key];const d=details[key];return <>
<section className="productHero"><div className="shell productHeroGrid"><div><div className="eyebrow">EZHARU {p.name.toUpperCase()}</div><ProductMark product={key}/><h1>{d.headline}</h1><p>{d.sub}</p><div className="actions"><Link className="btn" href="/contact">Talk to us →</Link><Link className="btn ghost" href="/products">All products</Link></div></div><div className={`productMock ${key}`}><div className="mockWindow"><div className="mockBar"><i/><i/><i/></div><div className="mockBody"><span className="bigFeature"><Icon type={p.icon}/></span><small>EZHaru {p.name}</small><strong>{p.tagline}</strong><div className="mockLines"><i/><i/><i/><i/></div></div></div></div></div></section>
<section className="section"><div className="shell"><div className="sectionHead"><div className="eyebrow">CORE CAPABILITIES</div><h2>Focused on the work that matters.</h2></div><div className="featureGrid">{d.features.map(([icon,title,copy])=><article key={title}><span><Icon type={icon}/></span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
<section className="section softSection"><div className="shell"><div className="sectionHead"><div className="eyebrow">SIMPLE FLOW</div><h2>Easy to understand. Easy to adopt.</h2></div><div className="flowLine">{d.flow.map((x,i)=><div key={x}><span>{String(i+1).padStart(2,'0')}</span><b>{x}</b>{i<d.flow.length-1&&<i>→</i>}</div>)}</div></div></section>
<section className="section"><div className="shell quotePanel"><div className="eyebrow">THE POINT</div><h2>{d.closing}</h2><p>{p.audience}</p></div></section><CTA/>
</>}
