import {notFound} from 'next/navigation';
import Link from 'next/link';
import {CTA, Icon, ProductKey, ProductMark, productInfo} from '@/components/BrandSystem';

const keys:ProductKey[]=['recorder','expense','invoice','class'];
const details:Record<ProductKey,{eyebrow:string;headline:string;sub:string;features:[string,string,string][];flow:string[];principle:string;closing:string}>={
 recorder:{eyebrow:'CONVERSATIONS → KNOWLEDGE',headline:'Capture what was said. Keep what matters.',sub:'EZHaru Recorder turns calls and meetings into organized, searchable knowledge so the useful part of a conversation does not disappear when the meeting ends.',features:[['wave','Recording workflow','Keep conversations available for review instead of relying on memory.'],['document','Transcription & summaries','Turn spoken information into clear written context.'],['search','Searchable history','Find past discussions, decisions and commitments more easily.'],['link','Useful follow-up','Keep important context available after the conversation.']],flow:['Record a call or meeting','Transcribe the conversation','Summarize key points and actions','Organize it for later retrieval'],principle:'Recording is only the first step.',closing:'The value is what happens after the conversation: finding the decision, remembering the commitment, and turning discussion into work.'},
 expense:{eyebrow:'RECEIPTS → CLEAN DATA',headline:'Receipts in. Repetitive work out.',sub:'EZHaru Expense is designed to reduce the repeated work between a receipt and clean, reviewable expense data — while keeping people in the loop where judgment matters.',features:[['receipt','Receipt capture','Bring receipts into one consistent workflow.'],['document','Structured expense data','Turn receipt details into reviewable information.'],['search','Exception review','Make uncertain items easier to see and resolve.'],['link','Accounting-ready output','Prepare approved data for the next accounting step.']],flow:['Capture or upload a receipt','Extract and organize the details','Review exceptions','Prepare approved data for accounting'],principle:'Automation should reduce review, not remove control.',closing:'Standard items can move quickly. Exceptions should become easier to see, easier to explain and easier to resolve.'},
 invoice:{eyebrow:'WORK DONE → PAYMENT VISIBILITY',headline:'Invoicing made simple.',sub:'EZHaru Invoice is designed to keep invoice creation, delivery and payment visibility straightforward for small teams.',features:[['document','Invoice creation','Create clean, consistent invoices from a simple workflow.'],['link','Delivery workflow','Keep invoice sending and follow-up visible.'],['search','Payment visibility','Know what is open without digging through disconnected files.'],['gear','Repeatable process','Reduce unnecessary manual steps around recurring billing work.']],flow:['Create the invoice','Send it to the customer','Track status','Follow payment progress'],principle:'Clarity matters more than complexity.',closing:'The product is designed around a small team’s real questions: what was sent, what is pending and what needs follow-up.'},
 class:{eyebrow:'MEMBERS → CLASSES → PROGRESS',headline:'Run the class, not the paperwork.',sub:'EZHaru Class starts with martial arts schools and dojangs, with a broader foundation for other class-based organizations as the product grows.',features:[['people','Member management','Keep member information organized and easy to work with.'],['document','Schedules & attendance','Manage classes and participation in one flow.'],['layers','Progress & rank','Support belt, rank or level progression without locking the product to one industry.'],['link','Operational visibility','Make the next action easier to see for staff and owners.']],flow:['Manage members','Schedule classes','Track attendance','Follow rank or learning progress'],principle:'Built from a dojang. Designed beyond one dojang.',closing:'Rank and belt progression are the starting use case, but the underlying model is about classes, attendance and progress — concepts that travel well to other training businesses.'}
};

export function generateStaticParams(){return keys.map(slug=>({slug}));}

export default async function ProductPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;if(!keys.includes(slug as ProductKey))notFound();const key=slug as ProductKey;const p=productInfo[key];const d=details[key];return <>
<section className="productHero productHeroV3"><div className="shell productHeroGrid"><div><ProductMark product={key}/><div className="eyebrow">{d.eyebrow}</div><h1>{d.headline}</h1><p>{d.sub}</p><div className="actions"><Link className="btn" href="/contact">Talk with EZHaru →</Link><Link className="btn ghost" href="/products">All Products</Link></div></div><div className={`productWorkspace ${key}`}><div className="workspaceBar"><i/><i/><i/><small>EZHaru {p.name}</small></div><div className="workspaceBody"><aside><ProductMark product={key} badge/><span className="active">Overview</span><span>Recent</span><span>Review</span><span>Settings</span></aside><section><small>SIMPLE WORKFLOW</small><h3>{p.tagline}</h3>{d.flow.map((x,i)=><div className="workflowRow" key={x}><b>{String(i+1).padStart(2,'0')}</b><span>{x}</span><Icon type="check"/></div>)}</section></div></div></div></section>
<section className="section"><div className="shell"><div className="sectionHead"><div className="eyebrow">CORE CAPABILITIES</div><h2>Focused on the work that matters.</h2></div><div className="featureGrid">{d.features.map(([icon,title,copy])=><article key={title}><span><Icon type={icon}/></span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
<section className="section softSection"><div className="shell splitPanel"><div><div className="eyebrow">EZHARU PRINCIPLE</div><h2>{d.principle}</h2><p>{d.closing}</p><Link className="textLink" href="/how-we-work">See how we work →</Link></div><div className="productPrincipleCard"><span><Icon type="layers"/></span><b>Start with the process.</b><p>Then use the lightest technology that makes the work clearer, faster and easier.</p></div></div></section><CTA/>
</>}
